@Library('jenkins-upstream-library') _
pipeline {
    agent {
        docker {
            image 'quay.io/powercloud/inbound-agent:3256.v88a_f6e922152-2-jdk17.1'
            args '-v /etc/resolv.conf:/etc/resolv.conf.tmp '
            label 'jump-vpc-x86_64'
        }
    }
    environment {
        //users and credentials. All must be defined in Jenkins Credentials
        GITHUB_TOKEN = credentials('GITHUB_TOKEN')
        OS_USERNAME = credentials('OS_USERNAME')
        OS_PASSWORD = credentials('OS_PASSWORD')

        OCP_RELEASE = "4.16"
	 }
    stages {
        stage('Setup Common Environment Variables') {
            steps {
                setupCommonEnvironmentVariables()
            }
        }
        stage('Prepare Terraform Template') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try
                    {

                        sh '''
                            openstack image list --insecure --format value -c Name -c ID > images.scnlcicdcloud.all.txt
                            for i in `cat images.scnlcicdcloud.all.txt|grep "cicd-*" |awk '{print $2}'`; do line=$(grep $i images.scnlcicdcloud.all.txt) ;  create_date=$(openstack image show $i --insecure | grep created_at | awk  'BEGIN{FS="|"}{print $3}' | sed 's/ *$//') ; echo -n  $line" " >> images.scnlcicdcloud.all.date.txt; echo $create_date >> images.scnlcicdcloud.all.date.txt ;done
                            cat images.scnlcicdcloud.all.date.txt | sort -k3 -r > images.scnlcicdcloud.all.date.sorted.txt
                            cat images.scnlcicdcloud.all.date.sorted.txt | grep -v ssp | grep 'cicd-rhcos-4\\.11\\|cicd-rhcos-411' | awk '{print $2" "$1}'|head -n 1 > cicd-rhcos-4.11.latest.txt || true
                            cat images.scnlcicdcloud.all.date.sorted.txt | grep -v ssp | grep 'cicd-rhcos-4\\.12\\|cicd-rhcos-412' | awk '{print $2" "$1}'|head -n 1 > cicd-rhcos-4.12.latest.txt || true
                            cat images.scnlcicdcloud.all.date.sorted.txt | grep -v ssp | grep 'cicd-rhcos-4\\.13\\|cicd-rhcos-413' | awk '{print $2" "$1}'|head -n 1 > cicd-rhcos-4.13.latest.txt || true
                            cat images.scnlcicdcloud.all.date.sorted.txt | grep -v ssp | grep 'cicd-rhcos-4\\.14\\|cicd-rhcos-414' | awk '{print $2" "$1}'|head -n 1 > cicd-rhcos-4.14.latest.txt || true
                            cat images.scnlcicdcloud.all.date.sorted.txt | grep -v ssp | grep 'cicd-rhcos-4\\.15\\|cicd-rhcos-415' | awk '{print $2" "$1}'|head -n 1 > cicd-rhcos-4.15.latest.txt || true
                            cat images.scnlcicdcloud.all.date.sorted.txt | grep -v ssp | grep 'cicd-rhcos-4\\.16\\|cicd-rhcos-416' | awk '{print $2" "$1}'|head -n 1 > cicd-rhcos-4.16.latest.txt || true
                            cat images.scnlcicdcloud.all.date.sorted.txt | grep -v ssp | grep 'cicd-rhcos-4\\.17\\|cicd-rhcos-417' | awk '{print $2" "$1}'|head -n 1 > cicd-rhcos-4.17.latest.txt || true

                            cat images.scnlcicdcloud.all.date.sorted.txt | grep -v ssp | grep 'cicd-rhel8\\.3'  | awk '{print $2" "$1}'|head -n 1 > cicd-rhel-8.3.latest.txt || true
                            cat images.scnlcicdcloud.all.date.sorted.txt | grep -v ssp | grep 'cicd-rhel8\\.4'  | awk '{print $2" "$1}'|head -n 1 > cicd-rhel-8.4.latest.txt || true
                            cat images.scnlcicdcloud.all.date.sorted.txt | grep -v ssp | grep 'cicd-rhel8\\.5'  | awk '{print $2" "$1}'|head -n 1 > cicd-rhel-8.5.latest.txt || true
                            cat images.scnlcicdcloud.all.date.sorted.txt | grep -v ssp | grep 'cicd-rhel8\\.6'  | awk '{print $2" "$1}'|head -n 1 > cicd-rhel-8.6.latest.txt || true
                            cat images.scnlcicdcloud.all.date.sorted.txt | grep -v ssp | grep 'cicd-rhel9\\.0'  | awk '{print $2" "$1}'|head -n 1 > cicd-rhel-9.0.latest.txt || true
                            cat images.scnlcicdcloud.all.date.sorted.txt | grep -v ssp | grep 'cicd-rhel9\\.2'  | awk '{print $2" "$1}'|head -n 1 > cicd-rhel-9.2.latest.txt || true
                            cat images.scnlcicdcloud.all.date.sorted.txt | grep -v ssp | grep 'cicd-rhel9\\.3'  | awk '{print $2" "$1}'|head -n 1 > cicd-rhel-9.3.latest.txt || true
                            cat images.scnlcicdcloud.all.date.sorted.txt | grep -v ssp | grep 'cicd-rhel9\\.4'  | awk '{print $2" "$1}'|head -n 1 > cicd-rhel-9.4.latest.txt || true
                        '''

                    }

                    catch (err)
                    {
                        echo 'Error ! Pulling images failed !'
                        throw err
                    }
                }
            }
        }
    }
    post {
        always {
            archiveAllArtifacts("cicd-rhcos-4.11.latest.txt", "cicd-rhcos-4.12.latest.txt", "cicd-rhcos-4.13.latest.txt",
                                "cicd-rhcos-4.14.latest.txt", "cicd-rhcos-4.15.latest.txt", "cicd-rhcos-4.16.latest.txt", 
                                "cicd-rhcos-4.17.latest.txt", "cicd-rhel-8.2.latest.txt", "cicd-rhel-8.3.latest.txt",
                                "cicd-rhel-8.4.latest.txt", "cicd-rhel-8.5.latest.txt" , "cicd-rhel-8.6.latest.txt", 
                                "cicd-rhel-9.0.latest.txt", "cicd-rhel-9.2.latest.txt", "cicd-rhel-9.3.latest.txt", 
                                "cicd-rhel-9.4.latest.txt")
            cleanWs()
        }
    }
}