@Library('jenkins-upstream-library') _
//Define Global variable
def INSTANCE_NAME_LIST = [
                    "rdr-ocp-cicd-montreal01",
                    "rdr-ocp-upi-validation-osa21",
                    "rdr-ocp-upi-validation-tor01",
                    "rdr-ocp-storage-sao01-odf",
                    "rdr-ocp-storage-lon06-odf",
                    "rdr-ocp-storage-syd05-odf",
                    "rdr-ocp-storage-osa21-odf"
                    ]
pipeline {
    agent {
        kubernetes {
            inheritFrom 'jenkins-agent'
        }
    }
    options {
        copyArtifactPermission('*');
    }
    environment {
        //users and credentials. All must be defined in Jenkins Credentials
        IBM_CLOUD_API_KEY = credentials('IBMCLOUD_UPSTREAM_CI_API_KEY')
        PCLOUD_IBM_API_KEY = credentials('IBM_PCLOUD_QE_API_KEY')
        ODF_IBMCLOUD_API_KEY = credentials('ODF_IBMCLOUD_API_KEY')
        PVSADM_VERSION = "v0.1.15"
    }
    stages {
        stage('Pull PowerVS Images') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    sh(returnStatus: false, returnStdout: false, script: "curl -sL https://raw.githubusercontent.com/ppc64le-cloud/pvsadm/${PVSADM_VERSION}/get.sh | VERSION=${PVSADM_VERSION} FORCE=1 bash; pvsadm version")
                    INSTANCE_NAME_LIST.each { item ->
                        if(item.matches("rdr-ocp-upi-validation-(.*)")){
                            env.IBMCLOUD_API_KEY = env.PCLOUD_IBM_API_KEY
                        }
                        else if(item.matches("(.*)odf(.*)")){
                            env.IBMCLOUD_API_KEY = env.ODF_IBMCLOUD_API_KEY
                        }
                        else {
                            env.IBMCLOUD_API_KEY = env.IBM_CLOUD_API_KEY
                        }
                        sh """
                            pvsadm purge images --dry-run --workspace-name '${item}' |grep 'tier1' |grep 'active' > images_all_'${item}'.txt
                            cat images_all_'${item}'.txt | grep 'rhel-83'  |sort -t'|' -k5 -r|head -1|grep -o 'rhel-83-[[:alnum:]]*-tier1'|xargs > latest-rhel-83-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhel-84'  |sort -t'|' -k5 -r|head -1|grep -o 'rhel-84-[[:alnum:]]*-tier1'|xargs > latest-rhel-84-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhel-85'  |sort -t'|' -k5 -r|head -1|grep -o 'rhel-85-[[:alnum:]]*-tier1'|xargs > latest-rhel-85-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhel-86'  |sort -t'|' -k5 -r|head -1|grep -o 'rhel-86-[[:alnum:]]*-tier1'|xargs > latest-rhel-86-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhel-9'  |sort -t'|' -k5 -r|head -1|grep -o 'rhel-9-[[:alnum:]]*-tier1'|xargs > latest-rhel-9-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhel-92'  |sort -t'|' -k5 -r|head -1|grep -o 'rhel-92-[[:alnum:]]*-tier1'|xargs > latest-rhel-92-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhel-93'  |sort -t'|' -k5 -r|head -1|grep -o 'rhel-93-[[:alnum:]]*-tier1'|xargs > latest-rhel-93-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhel-94'  |sort -t'|' -k5 -r|head -1|grep -o 'rhel-94-[[:alnum:]]*-tier1'|xargs > latest-rhel-94-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhel-95'  |sort -t'|' -k5 -r|head -1|grep -o 'rhel-95-[[:alnum:]]*-tier1'|xargs > latest-rhel-95-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhel-96'  |sort -t'|' -k5 -r|head -1|grep -o 'rhel-96-[[:alnum:]]*-tier1'|xargs > latest-rhel-96-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhel-10'  |sort -t'|' -k5 -r|head -1|grep -o 'rhel-10-[[:alnum:]]*-tier1'|xargs > latest-rhel-10-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhcos-411' |sort -t'|' -k5 -r|head -1|grep -o 'rhcos-411-[[:alnum:]]*-tier1'|xargs > latest-rhcos-411-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhcos-412' |sort -t'|' -k5 -r|head -1|grep -o 'rhcos-412-[[:alnum:]]*-tier1'|xargs > latest-rhcos-412-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhcos-413' |sort -t'|' -k5 -r|head -1|grep -o 'rhcos-413-[[:alnum:]]*-tier1'|xargs > latest-rhcos-413-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhcos-414' |sort -t'|' -k5 -r|head -1|grep -o 'rhcos-414-[[:alnum:]]*-tier1'|xargs > latest-rhcos-414-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhcos-415' |sort -t'|' -k5 -r|head -1|grep -o 'rhcos-415-[[:alnum:]]*-tier1'|xargs > latest-rhcos-415-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhcos-416' |sort -t'|' -k5 -r|head -1|grep -o 'rhcos-416-[[:alnum:]]*-tier1'|xargs > latest-rhcos-416-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhcos-417' |sort -t'|' -k5 -r|head -1|grep -o 'rhcos-417-[[:alnum:]]*-tier1'|xargs > latest-rhcos-417-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhcos-418' |sort -t'|' -k5 -r|head -1|grep -o 'rhcos-418-[[:alnum:]]*-tier1'|xargs > latest-rhcos-418-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhcos-419' |sort -t'|' -k5 -r|head -1|grep -o 'rhcos-419-[[:alnum:]]*-tier1'|xargs > latest-rhcos-419-'${item}'.txt || true
                        """
                    }
                }
            }
        }
    }
    post {
        always {
            script{
                INSTANCE_NAME_LIST.each { item ->
                    archiveArtifacts allowEmptyArchive: true, artifacts: "images_all_${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhel-83-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhel-84-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhel-85-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhel-86-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhel-9-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhel-92-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhel-93-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhel-94-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhel-95-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhel-96-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhel-10-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhcos-411-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhcos-412-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhcos-413-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhcos-414-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhcos-415-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhcos-416-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhcos-417-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhcos-418-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhcos-419-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                }
            }
            cleanWs()
        }
    }
}
