@Library('jenkins-upstream-library') _
pipeline {
    agent {
        docker {
            image 'quay.io/powercloud/inbound-agent:3256.v88a_f6e922152-2-jdk17.1'
            args '-v /etc/resolv.conf:/etc/resolv.conf -v /run/containerd/containerd.sock:/run/containerd/containerd.sock'
            label 'jump-vpc-x86_64'
        }
    }
    options {
        copyArtifactPermission('*');
    }
    environment {
        //users and credentials. All must be defined in Jenkins Credentials
        ARTIFACTORY_USER = credentials('ARTIFACTORY_USER')
        ARTIFACTORY_TOKEN = credentials('ARTIFACTORY_TOKEN')
        CI_OCP_TOKEN = credentials('CI_OCP_TOKEN')
        DOCKER_REGISTRY = "docker-na.artifactory.swg-devops.com/sys-powercloud-docker-local"
    }
    stages {
        stage('Get images and push') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try
                    {
                    sh '''
                        cd ${WORKSPACE}/scripts
                        nerdctl login -u ${ARTIFACTORY_USER} -p ${ARTIFACTORY_TOKEN} ${DOCKER_REGISTRY}
                        oc login --token=${CI_OCP_TOKEN} --server=https://api.ci.l2s4.p1.openshiftapps.com:6443
                        oc registry login --skip-check --registry-config ~/.docker/config.json
                        ./mirror-images.sh || true
                    '''
                    }
                    catch (err)
                    {
                        echo 'Error ! Mirroring Failed!'
                        throw err
                    }
                }
            }
        }

        stage('Prepare Terraform Template') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try
                    {
                    sh '''
                    curl https://openshift-release-ppc64le.apps.ci.l2s4.p1.openshiftapps.com/ > builds.raw.txt
                    cat builds.raw.txt | grep -A 2 '<td class="text-monospace"' | grep -v '^--' | awk 'NR%3{printf "%s ",$0;next;}1'|grep -v 'Failed' |sed 's|\\([^/]*/\\)\\{4\\}[^>]*>\\([^>]*\\).*title[^"]*"\\([^"]*\\).*|\\2  \\3|' | sed 's/<\\/a//'| sort -k2 -r |awk -v registry="${DOCKER_REGISTRY}" '{print registry"/ocp-ppc64le/release-ppc64le:"$0}' > all-builds.txt
                    #All Builds
                    grep '4\\.8\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.8-builds.txt
                    grep '4\\.9\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.9-builds.txt
                    grep '4\\.10\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.10-builds.txt
                    grep '4\\.11\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.11-builds.txt
                    grep '4\\.12\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.12-builds.txt
                    grep '4\\.13\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.13-builds.txt
                    grep '4\\.14\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.14-builds.txt
                    grep '4\\.15\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.15-builds.txt
                    grep '4\\.16\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.16-builds.txt
                    grep '4\\.17\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.17-builds.txt

                    #Latest Builds
                    cat all-4.8-builds.txt|head -n 1|awk '{print $1}'  > latest-4.8-build.txt
                    cat all-4.9-builds.txt|head -n 1|awk '{print $1}'  > latest-4.9-build.txt
                    cat all-4.10-builds.txt|head -n 1|awk '{print $1}' > latest-4.10-build.txt
                    cat all-4.11-builds.txt|head -n 1|awk '{print $1}' > latest-4.11-build.txt
                    cat all-4.12-builds.txt|head -n 1|awk '{print $1}' > latest-4.12-build.txt
                    cat all-4.13-builds.txt|head -n 1|awk '{print $1}' > latest-4.13-build.txt
                    cat all-4.14-builds.txt|head -n 1|awk '{print $1}' > latest-4.14-build.txt
                    cat all-4.15-builds.txt|head -n 1|awk '{print $1}' > latest-4.15-build.txt
                    cat all-4.16-builds.txt|head -n 1|awk '{print $1}' > latest-4.16-build.txt
                    cat all-4.17-builds.txt|head -n 1|awk '{print $1}' > latest-4.17-build.txt

                    #All stable Builds
                    cat all-4.8-builds.txt | grep -v 'nightly\\|-rc\\|-fc\\|-ec' > all-4.8-stable-builds.txt
                    cat all-4.9-builds.txt | grep -v 'nightly\\|-rc\\|-fc\\|-ec' > all-4.9-stable-builds.txt
                    cat all-4.10-builds.txt | grep -v 'nightly\\|-rc\\|-fc\\|-ec' > all-4.10-stable-builds.txt
                    cat all-4.11-builds.txt | grep -v 'nightly\\|-rc\\|-fc\\|-ec' > all-4.11-stable-builds.txt
                    cat all-4.12-builds.txt | grep -v 'nightly\\|-rc\\|-fc\\|-ec' > all-4.12-stable-builds.txt
                    cat all-4.13-builds.txt | grep -v 'nightly\\|-rc\\|-fc\\|-ec' > all-4.13-stable-builds.txt
                    cat all-4.14-builds.txt | grep -v 'nightly\\|-rc\\|-fc\\|-ec' > all-4.14-stable-builds.txt
                    cat all-4.15-builds.txt | grep -v 'nightly\\|-rc\\|-fc\\|-ec' > all-4.15-stable-builds.txt
                    cat all-4.16-builds.txt | grep -v 'nightly\\|-rc\\|-fc\\|-ec' > all-4.16-stable-builds.txt
                    cat all-4.14-builds.txt | grep '\\-ec' > all-4.14-ec-builds.txt
                    cat all-4.14-builds.txt | grep '\\-rc' > all-4.14-rc-builds.txt
                    cat all-4.15-builds.txt | grep '\\-ec' > all-4.15-ec-builds.txt
                    cat all-4.15-builds.txt | grep '\\-rc' > all-4.15-rc-builds.txt
                    cat all-4.16-builds.txt | grep '\\-ec' > all-4.16-ec-builds.txt
                    cat all-4.17-builds.txt | grep '\\-ec' > all-4.17-ec-builds.txt
                    cat all-4.16-builds.txt | grep '\\-rc' > all-4.16-rc-builds.txt


                    #Latest stable build
                    cat all-4.8-stable-builds.txt |head -n 1|awk '{print $1}' > latest-4.8-stable-build.txt
                    cat all-4.9-stable-builds.txt |head -n 1|awk '{print $1}' > latest-4.9-stable-build.txt
                    cat all-4.10-stable-builds.txt |head -n 1|awk '{print $1}' > latest-4.10-stable-build.txt
                    cat all-4.11-stable-builds.txt |head -n 1|awk '{print $1}' > latest-4.11-stable-build.txt
                    cat all-4.12-stable-builds.txt |head -n 1|awk '{print $1}' > latest-4.12-stable-build.txt
                    cat all-4.13-stable-builds.txt |head -n 1|awk '{print $1}' > latest-4.13-stable-build.txt
                    cat all-4.14-stable-builds.txt |head -n 1|awk '{print $1}' > latest-4.14-stable-build.txt
                    cat all-4.15-stable-builds.txt |head -n 1|awk '{print $1}' > latest-4.15-stable-build.txt
                    cat all-4.16-stable-builds.txt |head -n 1|awk '{print $1}' > latest-4.16-stable-build.txt
                    cat all-4.14-ec-builds.txt |head -n 1|awk '{print $1}' > latest-4.14-ec-build.txt
                    cat all-4.14-rc-builds.txt |head -n 1|awk '{print $1}' > latest-4.14-rc-build.txt
                    cat all-4.15-rc-builds.txt |head -n 1|awk '{print $1}' > latest-4.15-rc-build.txt
                    cat all-4.15-ec-builds.txt |head -n 1|awk '{print $1}' > latest-4.15-ec-build.txt
                    cat all-4.16-ec-builds.txt |head -n 1|awk '{print $1}' > latest-4.16-ec-build.txt
                    cat all-4.17-ec-builds.txt |head -n 1|awk '{print $1}' > latest-4.17-ec-build.txt
                    cat all-4.16-rc-builds.txt |head -n 1|awk '{print $1}' > latest-4.16-rc-build.txt
                    '''
                    }
                    catch (err)
                    {
                        echo 'Error ! Template preparation failed !'
                        env.FAILED_STAGE=env.STAGE_NAME
                        throw err
                    }
                }
            }
        }
    }
    post {
        always {
            archiveAllArtifacts("builds.raw.txt", "all-builds.txt", "all-4.8-builds.txt","all-4.9-builds.txt",
                                  "all-4.10-builds.txt","all-4.11-builds.txt", "all-4.12-builds.txt", "all-4.13-builds.txt",
                                  "all-4.14-builds.txt", "all-4.15-builds.txt", "all-4.16-builds.txt", "all-4.17-builds.txt",
                                  "latest-4.8-build.txt", "latest-4.9-build.txt","latest-4.10-build.txt",
                                  "latest-4.11-build.txt","latest-4.12-build.txt", "latest-4.13-build.txt",
                                  "latest-4.14-build.txt", "latest-4.15-build.txt", "latest-4.16-build.txt", "latest-4.17-build.txt",
                                  "all-4.8-stable-builds.txt", "all-4.9-stable-builds.txt","all-4.10-stable-builds.txt",
                                  "all-4.11-stable-builds.txt","all-4.12-stable-builds.txt","all-4.13-stable-builds.txt", "all-4.14-stable-builds.txt", "all-4.15-stable-builds.txt", "all-4.16-stable-builds.txt",
                                  "all-4.14-ec-builds.txt", "all-4.14-rc-builds.txt", "all-4.15-ec-builds.txt", "all-4.15-rc-builds.txt", "all-4.16-ec-builds.txt", "all-4.17-ec-builds.txt", "all-4.16-rc-builds.txt",
                                  "latest-4.8-stable-build.txt", "latest-4.9-stable-build.txt", "latest-4.10-stable-build.txt",
                                  "latest-4.11-stable-build.txt", "latest-4.12-stable-build.txt","latest-4.13-stable-build.txt", "latest-4.14-stable-build.txt", "latest-4.15-stable-build.txt", "latest-4.16-stable-build.txt",
                                  "latest-4.14-ec-build.txt", "latest-4.14-rc-build.txt", "latest-4.15-rc-build.txt", "latest-4.15-ec-build.txt", "latest-4.16-ec-build.txt", "latest-4.17-ec-build.txt", "latest-4.16-rc-build.txt")
            cleanWs()
        }
    }
}
