@Library('jenkins-upstream-library') _
pipeline {
    agent {
        docker {
            image 'quay.io/powercloud/inbound-agent:3256.v88a_f6e922152-2-jdk17.1'
            args '-v /etc/resolv.conf:/etc/resolv.conf -v /run/containerd/containerd.sock:/run/containerd/containerd.sock'
            label 'jump-vpc-x86_64'
        }
    }
    options {
        copyArtifactPermission('*');
    }
    stages {

        stage('Download OCP Build info') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try
                    {
                    sh '''
                    curl https://openshift-release-multi.apps.ci.l2s4.p1.openshiftapps.com/ > builds.raw.txt
                    cat builds.raw.txt | grep -A 2 '<td class="text-monospace"' | grep -v '^--' | awk 'NR%3{printf "%s ",$0;next;}1'|grep -v 'Failed' |sed 's|\\([^/]*/\\)\\{4\\}[^>]*>\\([^>]*\\).*title[^"]*"\\([^"]*\\).*|\\2  \\3|' | sed 's/<\\/a//'| sort -k2 -r > raw-all-builds.txt

                    for build in $(cat raw-all-builds.txt|awk '{print $1}'); do
                      if echo $build | grep -q "nightly"; then
                        echo quay.io/openshift-release-dev/ocp-release-nightly:${build} >> all-builds.txt
                      else
                        if echo $build | grep -q "multi"; then
                            echo quay.io/openshift-release-dev/ocp-release:${build} >> all-builds.txt
                        else
                            echo quay.io/openshift-release-dev/ocp-release:${build}-multi >> all-builds.txt
                        fi
                      fi
                    done
                    grep '4\\.11\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.11-builds.txt
                    grep '4\\.12\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.12-builds.txt
                    grep '4\\.13\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.13-builds.txt
                    grep '4\\.14\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.14-builds.txt
                    grep '4\\.15\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.15-builds.txt
                    grep '4\\.16\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.16-builds.txt
                    grep '4\\.17\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.17-builds.txt
                    grep '4\\.18\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.18-builds.txt
                    grep '4\\.19\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.19-builds.txt

                    #Latest Builds
                    cat all-4.11-builds.txt|head -n 1|awk '{print $1}' > latest-4.11-build.txt
                    cat all-4.12-builds.txt|head -n 1|awk '{print $1}' > latest-4.12-build.txt
                    cat all-4.13-builds.txt|head -n 1|awk '{print $1}' > latest-4.13-build.txt
                    cat all-4.14-builds.txt|head -n 1|awk '{print $1}' > latest-4.14-build.txt
                    cat all-4.15-builds.txt|head -n 1|awk '{print $1}' > latest-4.15-build.txt
                    cat all-4.16-builds.txt|head -n 1|awk '{print $1}' > latest-4.16-build.txt
                    cat all-4.17-builds.txt|head -n 1|awk '{print $1}' > latest-4.17-build.txt
                    cat all-4.18-builds.txt|head -n 1|awk '{print $1}' > latest-4.18-build.txt
                    cat all-4.19-builds.txt|head -n 1|awk '{print $1}' > latest-4.19-build.txt

                    #All stable Builds
                    cat all-4.11-builds.txt | grep -v 'nightly\\|-rc\\|-fc\\|-ec' > all-4.11-stable-builds.txt
                    cat all-4.12-builds.txt | grep -v 'nightly\\|-rc\\|-fc\\|-ec' > all-4.12-stable-builds.txt
                    cat all-4.13-builds.txt | grep -v 'nightly\\|-rc\\|-fc\\|-ec' > all-4.13-stable-builds.txt
                    cat all-4.14-builds.txt | grep -v 'nightly\\|-rc\\|-fc\\|-ec' > all-4.14-stable-builds.txt
                    cat all-4.15-builds.txt | grep -v 'nightly\\|-rc\\|-fc\\|-ec' > all-4.15-stable-builds.txt
                    cat all-4.16-builds.txt | grep -v 'nightly\\|-rc\\|-fc\\|-ec' > all-4.16-stable-builds.txt
                    cat all-4.17-builds.txt | grep -v 'nightly\\|-rc\\|-fc\\|-ec' > all-4.17-stable-builds.txt
                    cat all-4.14-builds.txt | grep '\\-rc' > all-4.14-rc-builds.txt
                    cat all-4.15-builds.txt | grep '\\-rc' > all-4.15-rc-builds.txt
                    cat all-4.16-builds.txt | grep '\\-rc' > all-4.16-rc-builds.txt
                    cat all-4.17-builds.txt | grep '\\-rc' > all-4.17-rc-builds.txt
                    cat all-4.18-builds.txt | grep '\\-ec' > all-4.18-ec-builds.txt
                    cat all-4.18-builds.txt | grep '\\-rc' > all-4.18-rc-builds.txt
                    cat all-4.19-builds.txt | grep '\\-ec' > all-4.19-ec-builds.txt


                    #Latest stable build
                    cat all-4.11-stable-builds.txt |head -n 1|awk '{print $1}' > latest-4.11-stable-build.txt
                    cat all-4.12-stable-builds.txt |head -n 1|awk '{print $1}' > latest-4.12-stable-build.txt
                    cat all-4.13-stable-builds.txt |head -n 1|awk '{print $1}' > latest-4.13-stable-build.txt
                    cat all-4.14-stable-builds.txt |head -n 1|awk '{print $1}' > latest-4.14-stable-build.txt
                    cat all-4.15-stable-builds.txt |head -n 1|awk '{print $1}' > latest-4.15-stable-build.txt
                    cat all-4.16-stable-builds.txt |head -n 1|awk '{print $1}' > latest-4.16-stable-build.txt
                    cat all-4.17-stable-builds.txt |head -n 1|awk '{print $1}' > latest-4.17-stable-build.txt
                    cat all-4.14-rc-builds.txt |head -n 1|awk '{print $1}' > latest-4.14-rc-build.txt
                    cat all-4.15-rc-builds.txt |head -n 1|awk '{print $1}' > latest-4.15-rc-build.txt
                    cat all-4.16-rc-builds.txt |head -n 1|awk '{print $1}' > latest-4.16-rc-build.txt
                    cat all-4.17-rc-builds.txt |head -n 1|awk '{print $1}' > latest-4.17-rc-build.txt
                    cat all-4.18-ec-builds.txt |head -n 1|awk '{print $1}' > latest-4.18-ec-build.txt
                    cat all-4.18-rc-builds.txt |head -n 1|awk '{print $1}' > latest-4.18-rc-build.txt
                    cat all-4.19-ec-builds.txt |head -n 1|awk '{print $1}' > latest-4.19-ec-build.txt
                    '''
                    }
                    catch (err)
                    {
                        echo 'Error ! Download OCP Build info failed !'
                        env.FAILED_STAGE=env.STAGE_NAME
                        throw err
                    }
                }
            }
        }
    }
    post {
        always {
            archiveAllArtifacts("builds.raw.txt", "all-builds.txt", "all-4.11-builds.txt", "all-4.12-builds.txt", "all-4.13-builds.txt",
                                  "all-4.14-builds.txt", "all-4.15-builds.txt", "all-4.16-builds.txt", "all-4.17-builds.txt", "all-4.18-builds.txt", "all-4.19-builds.txt",
                                  "latest-4.11-build.txt","latest-4.12-build.txt", "latest-4.13-build.txt",
                                  "latest-4.14-build.txt", "latest-4.15-build.txt", "latest-4.16-build.txt", "latest-4.17-build.txt", "latest-4.18-build.txt", "latest-4.19-build.txt",
                                  "all-4.11-stable-builds.txt","all-4.12-stable-builds.txt","all-4.13-stable-builds.txt", "all-4.14-stable-builds.txt", "all-4.15-stable-builds.txt", "all-4.16-stable-builds.txt",  "all-4.17-stable-builds.txt",
                                  "all-4.14-rc-builds.txt", "all-4.15-rc-builds.txt", "all-4.16-rc-builds.txt", "all-4.17-rc-builds.txt", "all-4.18-rc-builds.txt",
                                  "latest-4.11-stable-build.txt", "latest-4.12-stable-build.txt","latest-4.13-stable-build.txt", "latest-4.14-stable-build.txt", "latest-4.15-stable-build.txt", "latest-4.16-stable-build.txt",  "latest-4.17-stable-build.txt",
                                  "latest-4.14-rc-build.txt", "latest-4.15-rc-build.txt", "latest-4.16-rc-build.txt", "latest-4.17-rc-build.txt","latest-4.18-rc-build.txt", "latest-4.18-ec-build.txt", "latest-4.19-ec-build.txt")
            cleanWs()
        }
    }
}
