@Library('jenkins-upstream-library') _
pipeline {
    agent {
        kubernetes {
            inheritFrom 'jenkins-agent'
        }
    }
    options {
        copyArtifactPermission('*');
    }
    stages {

        stage('Download OCP Build info') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try
                    {
                    sh '''#!/bin/bash -x
                    curl https://openshift-release-multi.apps.ci.l2s4.p1.openshiftapps.com/ > builds.raw.txt
                    cat builds.raw.txt | grep -A 2 '<td class="text-monospace"' | grep -v '^--' | awk 'NR%3{printf "%s ",$0;next;}1'|grep -vE 'Failed|.konflux-nightly-multi' |sed 's|\\([^/]*/\\)\\{4\\}[^>]*>\\([^>]*\\).*title[^"]*"\\([^"]*\\).*|\\2  \\3|' | sed 's/<\\/a//'| sort -k2 -r > raw-all-builds.txt
                    for build in $(cat raw-all-builds.txt|awk '{print $1}'); do
                      if echo $build | grep -q "nightly"; then
                        echo quay.io/openshift-release-dev/ocp-release-nightly:${build} >> all-builds.txt
                      else
                        if echo $build | grep -q "multi"; then
                            echo quay.io/openshift-release-dev/ocp-release:${build} >> all-builds.txt
                        else
                            echo quay.io/openshift-release-dev/ocp-release:${build}-multi >> all-builds.txt
                        fi
                      fi
                    done
                    for release in 4.15 4.16 4.17 4.18 4.19 4.20 4.21 4.22 4.23 5.0; do
                      grep "${release//./\\.}\\.[0-9]\\?[0-9]" all-builds.txt > all-${release}-builds.txt
                      cat all-${release}-builds.txt | head -n 1 | awk '{print $1}' > latest-${release}-build.txt
                    done

                    for release in 4.15 4.16 4.17 4.18 4.19 4.20 4.21 4.22; do
                      cat all-${release}-builds.txt | grep -v 'nightly\\|-rc\\|-fc\\|-ec' > all-${release}-stable-builds.txt
                      cat all-${release}-stable-builds.txt | head -n 1 | awk '{print $1}' > latest-${release}-stable-build.txt
                    done

                    for release in 4.23 5.0; do
                      cat all-${release}-builds.txt | grep '\\-ec' > all-${release}-ec-builds.txt
                      cat all-${release}-ec-builds.txt | head -n 1 | awk '{print $1}' > latest-${release}-ec-build.txt
                    done
                    '''
                    }
                    catch (err)
                    {
                        echo 'Error ! Download OCP Build info failed !'
                        env.FAILED_STAGE=env.STAGE_NAME
                        throw err
                    }
                }
            }
        }
    }
    post {
        always {
            archiveAllArtifacts("builds.raw.txt", "all-builds.txt", "all-4.15-builds.txt", "all-4.16-builds.txt", "all-4.17-builds.txt", "all-4.18-builds.txt", "all-4.19-builds.txt", "all-4.20-builds.txt", "all-4.21-builds.txt", "all-4.22-builds.txt", "all-4.23-builds.txt", "all-5.0-builds.txt",
                                  "latest-4.15-build.txt", "latest-4.16-build.txt", "latest-4.17-build.txt", "latest-4.18-build.txt", "latest-4.19-build.txt", "latest-4.20-build.txt", "latest-4.21-build.txt", "latest-4.22-build.txt", "latest-4.23-build.txt", "latest-5.0-build.txt",
                                  "all-4.15-stable-builds.txt", "all-4.16-stable-builds.txt", "all-4.17-stable-builds.txt", "all-4.18-stable-builds.txt", "all-4.19-stable-builds.txt", "all-4.20-stable-builds.txt", "all-4.21-stable-builds.txt", "all-4.22-stable-builds.txt", "all-4.23-ec-builds.txt", "all-5.0-ec-builds.txt",
                                  "latest-4.15-stable-build.txt", "latest-4.16-stable-build.txt", "latest-4.17-stable-build.txt", "latest-4.18-stable-build.txt", "latest-4.19-stable-build.txt", "latest-4.20-stable-build.txt", "latest-4.21-stable-build.txt", "latest-4.22-stable-build.txt", "latest-4.23-ec-build.txt", "latest-5.0-ec-build.txt")
            cleanWs()
        }
    }
}
